feat: intégration section competence
luger95/maquette0 pull request #3
Opened 2024-10-03 14:56 UTC by GatienFrenchDev

Intégration en HTML/CSS/JS de la section compétences de la maquette Adobe xd

2024-10-03 15:17 UTC, luger95 requested changes
Quelques éléments à revoir. Plus particulièrement sur le renommage des images, assures toi que tu seras le seul à les utiliser.

Dans l'ensemble c'est top

2024-10-03 15:17 UTC, luger95 commented on assets/css/globalStyle.css
> -    --blue-color: rgba(162, 182, 223, 1)
Pourquoi supprimer cette variable ? Peut-être que tes camarades en ont besoin

2024-10-03 15:17 UTC, luger95 commented on assets/css/competences.css
> +}
Les typos sont déjà importé depuis le fichier globalStyle, tu n'as pas besoin de les réimporter.

2024-10-03 15:17 UTC, luger95 commented on assets/css/competences.css
> +div#competence-container {
ici, tu n'as pas besoin de précisé que l'élément est sur une div. Un ID est uniquement sur une page

2024-10-03 15:17 UTC, luger95 commented on assets/js/competences/classes/Pagination.js
> +        document.querySelector('span#competence-pagination-total-pages').innerHTML = this.nbTotalPages > 9 ? this.nbTotalPages : `0${this.nbTotalPages}`;
Cibler ton élément à l'aide d'un span, n'est pas utile ici. Tu peux l'enlever

2024-10-03 15:17 UTC, luger95 commented on assets/js/competences/classes/Pagination.js
> +        if(this.index == this.nbTotalPages){
```suggestion
        if(this.index === this.nbTotalPages){
```

2024-10-03 15:17 UTC, luger95 commented on index.html
> +    <link rel="stylesheet" href="assets/css/globalStyle.css">
Tu dois charger ce fichier, après le reset

2024-10-03 15:38 UTC, GatienFrenchDev commented on assets/css/competences.css
> +div#competence-container {
Pour la lisibilité du code, je préfère garder le type d'élément ciblé

2024-10-03 15:38 UTC, GatienFrenchDev commented on assets/js/competences/classes/Pagination.js
> +        document.querySelector('span#competence-pagination-total-pages').innerHTML = this.nbTotalPages > 9 ? this.nbTotalPages : `0${this.nbTotalPages}`;
idem ici

2024-10-03 15:39 UTC, GatienFrenchDev commented on assets/css/competences.css
> +}
le fichier globalStyle n'existait pas dans le fichier du repo que j'avais cloné

2024-10-03 15:39 UTC, GatienFrenchDev commented on assets/css/globalStyle.css
> -    --blue-color: rgba(162, 182, 223, 1)
elle n'existait pas dans la version du repo que j'ai cloné

2024-10-03 16:08 UTC, GatienFrenchDev commented on assets/css/reset.css
> +  }
Le formatteur de VSCode s'est déclenché sur le fichier reset.css…

2024-10-10 08:44 UTC, luger95 commented on assets/css/competences.css
> +div#competence-container {
Ton raisonnement est juste. Malgré tout, donner l'information comme quoi le style est appliqué à une div, n'est pas utile, ici et complexifie la lecture du css. Tu peux donc supprimer ces déclarations.

2024-10-10 08:47 UTC, luger95 commented on assets/js/competences/classes/Pagination.js
> +        document.querySelector('span#competence-pagination-total-pages').innerHTML = this.nbTotalPages > 9 ? this.nbTotalPages : `0${this.nbTotalPages}`;
Mon retour sera identique à celui du dessus, à propos du css. 
Préciser l'élément HTML donne l'impression que ton élément `#competence-pagination-total-pages` peut-être présent aussi sur un autre élément HTML qu'un span. Ce qui n'est pas le cas dans ton application

2024-10-10 08:50 UTC, luger95 requested changes
Un dernier effort et on sera bon !

2024-10-10 08:50 UTC, luger95 commented on index.html
> +    <script src="assets/js/competences/classes/Pagination.js" defer></script>
Tu peux renommer ton fichier avec un "p" en minuscule ?

2024-10-10 09:26 UTC, GatienFrenchDev commented on index.html
> +    <script src="assets/js/competences/classes/Pagination.js" defer></script>
Oui, corrigé https://github.com/luger95/maquette0/pull/3/commits/119d5000f5c5ada212f06b1020e29c2f5a65f018

2024-10-10 09:27 UTC, GatienFrenchDev commented on assets/js/competences/classes/Pagination.js
> +        document.querySelector('span#competence-pagination-total-pages').innerHTML = this.nbTotalPages > 9 ? this.nbTotalPages : `0${this.nbTotalPages}`;
Ok, corrigé https://github.com/luger95/maquette0/pull/3/commits/9669c897572ae0eb47a4a79e89ce4f32121865f7

2024-10-10 09:28 UTC, GatienFrenchDev commented on assets/css/competences.css
> +div#competence-container {
Ok, corrigé https://github.com/luger95/maquette0/pull/3/commits/351f39a792e75b1a1ace1f1730b36e249a430b80

2024-10-17 08:28 UTC, luger95 approved these changes

2024-10-17 08:29 UTC, merged