Groupe/g2 a deschamps alexis
luger95/maquette0 pull request #4
Opened 2024-10-03 15:19 UTC by FunkyFight

c'est beau et ça marche, de toute façon je ne suis pas assez payé pour ce travail, un jour je ferais virer Bernard le senior dev

2024-10-03 15:28 UTC, luger95 requested changes
Dans l'ensemble, c'est bien. Quelques éléments sont à revoir, rien de bien méchant

2024-10-03 15:28 UTC, luger95 commented on assets/js/experts.js
> +let pixelPerSlide = -470;
Tu pourras calculer la taille directement

2024-10-03 15:28 UTC, luger95 commented on assets/js/experts.js
> +    if(slideNumber == 1) expertiseLeftArrow.style.color = "gray"; else expertiseLeftArrow.style.color = "white";
un saut de ligne après les ; c'est mieux pour la lisibilité

2024-10-03 15:28 UTC, luger95 commented on assets/js/experts.js
> +    if(slideNumber == 1) expertiseLeftArrow.style.color = "gray"; else expertiseLeftArrow.style.color = "white";
```suggestion
    if(slideNumber === 1) expertiseLeftArrow.style.color = "gray"; else expertiseLeftArrow.style.color = "white";
```

2024-10-03 15:28 UTC, luger95 commented on experts.css
> +
espaces inutiles

2024-10-03 15:28 UTC, luger95 commented on index.html
> +            <h3 id="experts-subtitle">PROXIMITÉ - PARTAGE - ENGAGEMENT - DÉPASSEMENT DE SOI - ÉLÉGANCE</h3>
Cela n'est pas un titre, mais une liste de mots clés

2024-10-03 15:41 UTC, FunkyFight commented on assets/js/experts.js
> +let pixelPerSlide = -470;
J'ai changé pixelPerSlide en une constante PIXELPERSLIDE. Il s'agit du nombre de pixel nécessaire à déplacer pour avoir la prochaine slide. Je ne suis pas sûr de comment calculer cette valeur.

Voir commit https://github.com/luger95/maquette0/commit/0adcdb5796575ba96d495f0d60a2535bc8bd9b9b

2024-10-03 15:41 UTC, FunkyFight commented on assets/js/experts.js
> +    if(slideNumber == 1) expertiseLeftArrow.style.color = "gray"; else expertiseLeftArrow.style.color = "white";
Corrigé https://github.com/luger95/maquette0/commit/0adcdb5796575ba96d495f0d60a2535bc8bd9b9b

2024-10-03 15:41 UTC, FunkyFight commented on assets/js/experts.js
> +    if(slideNumber == 1) expertiseLeftArrow.style.color = "gray"; else expertiseLeftArrow.style.color = "white";
Corrigé https://github.com/luger95/maquette0/commit/0adcdb5796575ba96d495f0d60a2535bc8bd9b9b

2024-10-03 15:41 UTC, FunkyFight commented on experts.css
> +
Corrigé mais profondément scandalisé https://github.com/luger95/maquette0/commit/0adcdb5796575ba96d495f0d60a2535bc8bd9b9b

2024-10-03 15:41 UTC, FunkyFight commented on index.html
> +            <h3 id="experts-subtitle">PROXIMITÉ - PARTAGE - ENGAGEMENT - DÉPASSEMENT DE SOI - ÉLÉGANCE</h3>
Corrigé https://github.com/luger95/maquette0/commit/0adcdb5796575ba96d495f0d60a2535bc8bd9b9b

2024-10-09 13:03 UTC, GatienFrenchDev commented on experts.css
> +
hahahaha

2024-10-10 08:40 UTC, luger95 requested changes
Plus que quelques ajustements

2024-10-10 08:40 UTC, luger95 commented on assets/js/experts.js
> +}
On ne comprends pas ce que fait cette fonction. Son nommage mérite d'être réviser.

2024-10-10 08:40 UTC, luger95 commented on assets/js/experts.js
> +    else expertiseRightArrow.style.color = "white";
Tu devrais définir des accolades, ca aiderait à lire ton code

2024-10-10 08:40 UTC, luger95 commented on assets/js/experts.js
> +    if(slideNumber == 1) expertiseLeftArrow.style.color = "gray";
```suggestion
    if(slideNumber === 1) expertiseLeftArrow.style.color = "gray"; 
```

2024-10-10 08:40 UTC, luger95 commented on assets/js/experts.js
> +    if(slideNumber == numberOfSlides - 3) expertiseRightArrow.style.color = "gray";
```suggestion
    if(slideNumber === numberOfSlides - 3) expertiseRightArrow.style.color = "gray"; 
```

2024-10-17 10:05 UTC, luger95 approved these changes

2024-10-17 10:15 UTC, merged